/**
 * Visual preview: what /today (homepage) might look like.
 *
 * Static mockup — no DB, no AI. Hero image is a one-shot byōbu cover
 * generated by gpt-image-1.5 (see scripts/generate-byobu-preview.ts);
 * city cards use placeholder Once-voice text and milk/eggs prices.
 *
 * The point is for the editor to react to the *aesthetic* before we
 * wire real ingest into this layout.
 */
import Link from "next/link";

export const metadata = { title: "Once · preview" };

interface PreviewCity {
  id: string;
  name: string;
  country: string;
  localTime: string;
  text: string;
  milk: string;
  eggs: string;
  hue: string; // CSS color for placeholder photo tile
}

// Placeholder content. Stories are written in Once voice as a stand-in
// — when ingest is wired up these become AI candidates that the editor
// picks/edits in /admin/today.
const CITIES: PreviewCity[] = [
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    localTime: "7:14 am",
    text: "茶碗放下的声音比电车更早。窗外没有人。她又坐了一会儿。",
    milk: "¥240",
    eggs: "¥288",
    hue: "#d6c4a8"
  },
  {
    id: "beijing",
    name: "Beijing",
    country: "China",
    localTime: "6:14 am",
    text: "胡同口的白雾里，卖豆浆的车还没开门。一只猫已经决定今天不睡了。",
    milk: "¥6.50",
    eggs: "¥12.80",
    hue: "#c9b89d"
  },
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    localTime: "3:44 am",
    text: "Versova fish market — the trucks arrive before the gulls. A boy folds yesterday's newspaper into a hat.",
    milk: "₹66",
    eggs: "₹78",
    hue: "#caa987"
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Türkiye",
    localTime: "1:14 am",
    text: "Bosphorus fog. The simit seller pushes his cart up the slope before the call to prayer.",
    milk: "₺36",
    eggs: "₺42",
    hue: "#b9a890"
  },
  {
    id: "london",
    name: "London",
    country: "UK",
    localTime: "11:14 pm (yest.)",
    text: "Rain on the cobbles outside a Hackney bakery. The baker turns the dough one last time before bed.",
    milk: "£1.45",
    eggs: "£2.95",
    hue: "#a8aa9c"
  },
  {
    id: "lagos",
    name: "Lagos",
    country: "Nigeria",
    localTime: "12:14 am",
    text: "Mile 12 market opens with one stall. The mangoes were picked before dawn yesterday in Benin.",
    milk: "₦1,800",
    eggs: "₦2,200",
    hue: "#c9a07a"
  },
  {
    id: "sao-paulo",
    name: "São Paulo",
    country: "Brazil",
    localTime: "8:14 pm (yest.)",
    text: "Avenida Paulista esvazia. Sob os jacarandás roxos, alguém esqueceu uma sacola da feira.",
    milk: "R$5.20",
    eggs: "R$11.50",
    hue: "#aa8a8e"
  },
  {
    id: "san-francisco",
    name: "San Francisco",
    country: "USA",
    localTime: "4:14 pm (yest.)",
    text: "Fog through the Sunset, a slow exhale. The crossing guard at 30th Avenue waves to no one.",
    milk: "$4.99",
    eggs: "$6.49",
    hue: "#9da093"
  },
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    localTime: "9:14 am",
    text: "First light at Watson's Bay. A sailboat unmoors. The cleaner at the ferry terminal hums something only she knows.",
    milk: "A$2.40",
    eggs: "A$6.80",
    hue: "#b8b59a"
  }
];

export default function PreviewToday() {
  return (
    <div className="page">
      <header className="masthead">
        <div className="brand">ONCE</div>
        <div className="date">april 25 · 2026</div>
        <div className="nav">
          <Link href="/preview/archive">archive →</Link>
        </div>
      </header>

      {/* Hero: byōbu cover, generated daily by gpt-image-1.5. */}
      <figure className="hero">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/preview/byobu.jpg"
          alt="A handscroll painting of nine cities at dawn"
        />
        <figcaption>nine ordinary mornings · april 25</figcaption>
      </figure>

      {/* Byōbu — horizontal scroll of 9 city panels. */}
      <section className="byobu" aria-label="today">
        {CITIES.map((c) => (
          <article key={c.id} className="panel">
            <div
              className="photo"
              style={{ background: `linear-gradient(135deg, ${c.hue} 0%, color-mix(in oklch, ${c.hue} 70%, #2A241D) 100%)` }}
            >
              <span className="photo-label">{c.id}</span>
            </div>
            <div className="meta">
              <h2>{c.name}</h2>
              <span className="country">{c.country}</span>
              <span className="time">{c.localTime}</span>
            </div>
            <p className="text">{c.text}</p>
            <div className="prices">
              <span>milk {c.milk}</span>
              <span className="sep">·</span>
              <span>eggs {c.eggs}</span>
            </div>
          </article>
        ))}
      </section>

      <footer className="colophon">
        <p className="hand">edited by Qi Liu &nbsp;·&nbsp; AI scans the wires; the words are mine</p>
        <p className="small">© Once 2026 &nbsp;·&nbsp; CC BY-NC &nbsp;·&nbsp; preview build</p>
      </footer>

      <style>{`
        :root {
          --paper:    #FAF4E8;
          --paper-2:  #F2EAD8;
          --ink:      #2A241D;
          --ink-2:    #5A4F44;
          --ink-faint:#8B7E6E;
          --rust:     #A55842;
          --sage:     #6E7E5E;
          --hairline: #C9BFAB;
        }

        .page {
          background: var(--paper);
          color: var(--ink);
          min-height: 100vh;
          padding: 0;
          font-family: "EB Garamond", "Source Serif 4", Georgia, serif;
          /* Subtle rice-paper grain via layered gradients. */
          background-image:
            radial-gradient(circle at 20% 30%, rgba(165,88,66,0.04) 0, transparent 60%),
            radial-gradient(circle at 80% 70%, rgba(110,126,94,0.04) 0, transparent 60%),
            repeating-linear-gradient(
              0deg,
              rgba(42,36,29,0.012) 0,
              rgba(42,36,29,0.012) 1px,
              transparent 1px,
              transparent 3px
            );
        }

        /* ── masthead ─────────────────────────────── */
        .masthead {
          max-width: 1100px;
          margin: 0 auto;
          padding: 28px 32px 14px;
          display: flex;
          align-items: baseline;
          justify-content: space-between;
          gap: 20px;
          border-bottom: 1px solid var(--hairline);
        }
        .brand {
          font-family: "EB Garamond", Georgia, serif;
          font-size: 36px;
          letter-spacing: 0.32em;
          font-weight: 500;
          color: var(--ink);
        }
        .date {
          font-family: "JetBrains Mono", "IBM Plex Mono", ui-monospace, monospace;
          font-size: 12px;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--ink-2);
        }
        .nav a {
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 11px;
          letter-spacing: 0.16em;
          text-transform: uppercase;
          color: var(--ink-faint);
          text-decoration: none;
          border-bottom: 1px dotted var(--hairline);
        }
        .nav a:hover { color: var(--ink); }

        /* ── hero scroll ──────────────────────────── */
        .hero {
          max-width: 1100px;
          margin: 18px auto 6px;
          padding: 0 32px;
        }
        .hero img {
          width: 100%;
          display: block;
          border-radius: 2px;
          /* subtle deckled edge feel */
          box-shadow:
            0 1px 0 rgba(42,36,29,0.06),
            0 24px 48px -28px rgba(42,36,29,0.18);
          /* breathing ken-burns animation, 60s loop */
          animation: breathe 60s ease-in-out infinite alternate;
          transform-origin: center center;
        }
        @keyframes breathe {
          0%   { transform: scale(1) translateX(0); }
          100% { transform: scale(1.04) translateX(-1.2%); }
        }
        figcaption {
          margin-top: 12px;
          text-align: center;
          font-style: italic;
          font-size: 14px;
          color: var(--ink-2);
          letter-spacing: 0.04em;
        }

        /* ── byōbu (horizontal nine-panel) ────────── */
        .byobu {
          max-width: 1100px;
          margin: 36px auto 32px;
          padding: 0 32px;
          display: grid;
          grid-template-columns: repeat(9, minmax(0, 1fr));
          gap: 0;
          border-top: 1px solid var(--hairline);
          border-bottom: 1px solid var(--hairline);
          background: linear-gradient(180deg, var(--paper) 0%, var(--paper-2) 100%);
        }
        @media (max-width: 1100px) {
          .byobu {
            display: flex;
            overflow-x: auto;
            scroll-snap-type: x mandatory;
            scrollbar-width: thin;
          }
          .panel { flex: 0 0 240px; scroll-snap-align: start; }
        }
        .panel {
          padding: 18px 14px 22px;
          border-right: 1px solid var(--hairline);
          display: flex;
          flex-direction: column;
          gap: 10px;
          position: relative;
          /* subtle highlight cycle — focuses each panel for ~6s in turn */
          animation: focus-cycle 54s linear infinite;
        }
        .panel:last-child { border-right: none; }

        /* Stagger each panel's animation by 6s so the focus walks east→west. */
        ${CITIES.map(
          (_, i) => `.panel:nth-child(${i + 1}) { animation-delay: -${i * 6}s; }`
        ).join("\n        ")}

        @keyframes focus-cycle {
          0%   { background: transparent; }
          /* peak highlight at the panel's slot */
          1%   { background: rgba(165,88,66,0.06); }
          5%   { background: rgba(165,88,66,0.10); }
          10%  { background: rgba(165,88,66,0.06); }
          12%  { background: transparent; }
          100% { background: transparent; }
        }

        .photo {
          aspect-ratio: 4 / 3;
          width: 100%;
          border-radius: 2px;
          position: relative;
          overflow: hidden;
          /* simulate a sepia photographic feel */
          filter: saturate(0.85);
          box-shadow: inset 0 0 0 1px rgba(42,36,29,0.06);
        }
        .photo-label {
          position: absolute;
          bottom: 6px;
          left: 8px;
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 9px;
          letter-spacing: 0.18em;
          color: rgba(250, 244, 232, 0.85);
          text-transform: uppercase;
        }

        .meta {
          display: flex;
          flex-wrap: wrap;
          gap: 6px;
          align-items: baseline;
          row-gap: 1px;
        }
        .meta h2 {
          margin: 0;
          font-family: "EB Garamond", Georgia, serif;
          font-size: 16px;
          font-weight: 500;
          letter-spacing: 0.04em;
          color: var(--ink);
        }
        .country {
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 9px;
          letter-spacing: 0.14em;
          text-transform: uppercase;
          color: var(--ink-faint);
        }
        .time {
          margin-left: auto;
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 10px;
          color: var(--ink-2);
          font-variant-numeric: tabular-nums;
        }

        .text {
          margin: 0;
          font-family: "EB Garamond", Georgia, serif;
          font-size: 13.5px;
          line-height: 1.5;
          color: var(--ink);
          font-style: italic;
        }
        .prices {
          margin-top: auto;
          padding-top: 8px;
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 10px;
          color: var(--ink-faint);
          letter-spacing: 0.06em;
          display: flex;
          gap: 6px;
          border-top: 1px dotted var(--hairline);
        }
        .prices .sep { color: var(--hairline); }

        /* ── colophon ─────────────────────────────── */
        .colophon {
          max-width: 1100px;
          margin: 32px auto 60px;
          padding: 24px 32px 0;
          border-top: 1px solid var(--hairline);
          text-align: center;
        }
        .hand {
          font-family: "EB Garamond", Georgia, serif;
          font-style: italic;
          font-size: 14px;
          color: var(--ink-2);
          margin: 0 0 6px;
        }
        .small {
          font-family: "JetBrains Mono", ui-monospace, monospace;
          font-size: 10px;
          letter-spacing: 0.12em;
          color: var(--ink-faint);
          text-transform: uppercase;
          margin: 0;
        }
      `}</style>
    </div>
  );
}
